//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingYourPackage.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public Shipment()
        {
            this.ShipmentStates = new HashSet<ShipmentState>();
        }
    
        public int ID { get; set; }
        public int AffiliateID { get; set; }
        public int ShipmentTypeID { get; set; }
        public decimal Price { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverSurname { get; set; }
        public string ReceiverAddress { get; set; }
        public string ReceiverZipCode { get; set; }
        public string ReceiverCity { get; set; }
        public string ReceiverCountry { get; set; }
        public string ReceiverTelephone { get; set; }
        public string ReceiverEmail { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Affiliate Affiliate { get; set; }
        public virtual ShipmentType ShipmentType { get; set; }
        public virtual ICollection<ShipmentState> ShipmentStates { get; set; }
    }
}
